# Lecture 10 — Docker Compose / Lecture 16 — Kubernetes Ingress
server {
    listen 80;

    # Static frontend
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    # Proxy to backend
    location /api/ {
        proxy_pass http://backend:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /health {
        proxy_pass http://backend:3000/health;
    }

    location /info {
        proxy_pass http://backend:3000/info;
    }

    # Prometheus — Lecture 21
    location /metrics {
        proxy_pass http://backend:3000/metrics;
    }
}
